#!/usr/bin/env python3
"""Sanity review of the deterministic data product (RECIPE's phase 1-5
checkpoint). Prints findings and writes reports/data_product_review.md.

Three kinds of look:
  CONSISTENCY  do the four parquets agree with each other on keys and counts?
  PHYSICS      do raw distributions point the way rock physics says they
               should -- and where they do not, is the confound the known one
               (operators drill good rock tightly)?
  SPOT WELLS   three named wells a human can eyeball end to end.
Train-era wells only for any target-vs-feature look: the holdout stays shut.
"""
from __future__ import annotations

import duckdb

from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from borehole_geometry import config as C  # noqa: E402

P = C.DATA_PROC
lines = ["# Data product review (phases 1-5)", "",
         "Generated by scripts/review_data_product.py.", ""]
con = duckdb.connect()

def say(txt=""):
    print(txt)
    lines.append(txt if txt else "")

say("== CONSISTENCY ==")
r = con.execute(f"""
    SELECT
      (SELECT count(*) FROM read_parquet('{P}/spacing_pairs.parquet') p
        WHERE NOT EXISTS (SELECT 1 FROM read_parquet('{P}/wells_legs.parquet') w
                          WHERE w.well_key = p.well_key)),
      (SELECT count(*) FROM read_parquet('{P}/spacing_pairs_ctx.parquet') c
        WHERE NOT EXISTS (SELECT 1 FROM read_parquet('{P}/spacing_pairs.parquet') p
                          WHERE p.well_key = c.well_key AND p.nbr_key = c.nbr_key)),
      (SELECT count(*) FROM read_parquet('{P}/cohort.parquet')
        WHERE length_class IS NOT NULL AND well_key NOT IN
              (SELECT well_key FROM read_parquet('{P}/wells_legs.parquet')))
""").fetchone()
say(f"  pairs with unknown geometry key: {r[0]}   ctx pairs absent from pairs: {r[1]}   "
    f"cohort-with-class missing legs: {r[2]}")
ok_keys = r == (0, 0, 0)

r = con.execute(f"""
    WITH d AS (SELECT well_key a, nbr_key b, dist_m FROM read_parquet('{P}/spacing_pairs.parquet'))
    SELECT count(*) FROM d x LEFT JOIN d y ON y.a = x.b AND y.b = x.a
    WHERE y.a IS NULL OR abs(x.dist_m - y.dist_m) > 0.01
""").fetchone()[0]
say(f"  direction pairs missing a mirror or disagreeing on distance: {r}")

say("")
say("== PHYSICS: does interference show up raw? (train-era targeted wells) ==")
say("  target%% of peer P50 by distance to nearest draining neighbour:")
rows = con.execute(f"""
    WITH t AS (SELECT c.well_key, c.target_pace_pct
               FROM read_parquet('{P}/cohort.parquet') c
               WHERE c.target_pace_pct IS NOT NULL AND NOT c.is_holdout_era),
    nb AS (SELECT well_key, min(dist_m) mind
           FROM read_parquet('{P}/spacing_pairs_ctx.parquet')
           WHERE nbr_boe_during > 0 GROUP BY 1)
    SELECT CASE WHEN nb.mind IS NULL THEN 'no draining nbr <2km'
                WHEN nb.mind < 200 THEN '<200 m' WHEN nb.mind < 400 THEN '200-400'
                WHEN nb.mind < 800 THEN '400-800' ELSE '800-2000' END bucket,
           count(*) n, round(median(t.target_pace_pct)) med_target
    FROM t LEFT JOIN nb USING (well_key)
    GROUP BY 1 ORDER BY min(coalesce(nb.mind, 99999))
""").fetchall()
for b, n, m in rows:
    say(f"    {b:<22} n={n:>6,}   median target {m:>4.0f}%")

say("  ...and by neighbour depletion before the subject's window:")
rows = con.execute(f"""
    WITH t AS (SELECT c.well_key, c.target_pace_pct
               FROM read_parquet('{P}/cohort.parquet') c
               WHERE c.target_pace_pct IS NOT NULL AND NOT c.is_holdout_era),
    nb AS (SELECT well_key, sum(nbr_cum_boe_before) cum
           FROM read_parquet('{P}/spacing_pairs_ctx.parquet') GROUP BY 1)
    SELECT CASE WHEN coalesce(cum,0)=0 THEN 'none' WHEN cum<1e5 THEN '<100k boe'
                WHEN cum<1e6 THEN '100k-1M' ELSE '>1M boe' END bucket,
           count(*) n, round(median(t.target_pace_pct)) med
    FROM t LEFT JOIN nb USING (well_key)
    GROUP BY 1 ORDER BY min(coalesce(cum,0))
""").fetchall()
for b, n, m in rows:
    say(f"    {b:<22} n={n:>6,}   median target {m:>4.0f}%")

iso = con.execute(f"""
    SELECT count(*) FROM read_parquet('{P}/cohort.parquet') c
    WHERE c.target_pace_pct IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM read_parquet('{P}/spacing_pairs_ctx.parquet') x
                      WHERE x.well_key = c.well_key AND x.nbr_boe_during > 0)
""").fetchone()[0]
say(f"  ISOLATED targeted wells (no draining nbr <2 km): {iso:,} "
    f"-- these anchor the counterfactual (lesson 09)")

say("")
say("== PHYSICS: cross-feature shape ==")
r = con.execute(f"""
    SELECT round(median(CASE WHEN same_play THEN abs(dz_m) END)),
           round(median(CASE WHEN NOT same_play THEN abs(dz_m) END))
    FROM read_parquet('{P}/spacing_pairs_ctx.parquet')""").fetchone()
say(f"  median |dz|: same-play {r[0]:.0f} m vs different-play {r[1]:.0f} m "
    f"(same-zone pairs should be flatter)")
r = con.execute(f"""
    SELECT p.play_name, count(*) n
    FROM read_parquet('{P}/spacing_pairs_ctx.parquet') x
    JOIN read_parquet('{P}/cohort.parquet') p USING (well_key)
    WHERE x.nbr_inj_steam_during > 0
    GROUP BY 1 ORDER BY n DESC LIMIT 3""").fetchall()
say(f"  steam-neighbour pairs, top subject plays: "
    f"{[(str(a)[:24], b) for a, b in r]}  (expect thermal country)")

say("")
say("== SPOT WELLS ==")
for label, sql in [
    ("busiest targeted subject",
     f"""SELECT well_key FROM (
         SELECT x.well_key, count(*) n FROM read_parquet('{P}/spacing_pairs_ctx.parquet') x
         JOIN read_parquet('{P}/cohort.parquet') c USING (well_key)
         WHERE c.target_pace_pct IS NOT NULL AND x.nbr_boe_during > 0 GROUP BY 1
         ORDER BY n DESC LIMIT 1)"""),
    ("an isolated targeted well",
     f"""SELECT c.well_key FROM read_parquet('{P}/cohort.parquet') c
         WHERE c.target_pace_pct IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM read_parquet('{P}/spacing_pairs_ctx.parquet') x
                           WHERE x.well_key = c.well_key) LIMIT 1"""),
    ("a steam-flanked subject",
     f"""SELECT x.well_key FROM read_parquet('{P}/spacing_pairs_ctx.parquet') x
         JOIN read_parquet('{P}/cohort.parquet') c USING (well_key)
         WHERE c.target_pace_pct IS NOT NULL
         GROUP BY 1 ORDER BY sum(x.nbr_inj_steam_during) DESC LIMIT 1"""),
]:
    wk = con.execute(sql).fetchone()
    if not wk:
        say(f"  [{label}] none found")
        continue
    wk = wk[0]
    c = con.execute(f"""SELECT operator_name, play_name, first_m, n_legs,
                               round(total_lateral_m), round(pace_boe_yr),
                               round(target_pace_pct), length_class
                        FROM read_parquet('{P}/cohort.parquet')
                        WHERE well_key='{wk}'""").fetchone()
    say(f"  [{label}] licence {wk} -- {c[0]}, {str(c[1])[:30]}, first {c[2]}")
    say(f"      {c[3]} legs / {c[4]:,.0f} m lateral ({c[7]}), "
        f"pace {c[5]:,.0f} boe/yr, target {c[6]:.0f}%")
    nb = con.execute(f"""SELECT nbr_key, round(dist_m), nbr_age_months,
                                round(nbr_cum_boe_before), round(nbr_boe_during),
                                round(nbr_inj_steam_during), nbr_censored
                         FROM read_parquet('{P}/spacing_pairs_ctx.parquet')
                         WHERE well_key='{wk}' ORDER BY dist_m LIMIT 4""").fetchall()
    for b in nb:
        say(f"      nbr {b[0]} @ {b[1]:>5,.0f} m  age {str(b[2]):>4} mo"
            f"{' (censored floor)' if b[6] else ''}  cum-before {b[3]:>11,.0f}"
            f"  during {b[4]:>9,.0f}  steam {b[5]:>9,.0f}")

out = C.REPORTS / "data_product_review.md"
out.write_text("\n".join(lines) + "\n")
print(f"\nwrote {out.relative_to(C.ROOT)}")
